# This file was generated by GoReleaser. DO NOT EDIT.
cask "che-beta" do
  version "1.0.0-rc.7"

  on_macos do
    on_intel do
      sha256 "1cac351f3d0044105a4446dce0e53cab0622b3d1f854110907dafe11051d9d8f"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "049ee2ac4eb4914fa54c2f86437222a6084122a72de264ddf33370f3d35058bf"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26dbd48071b1d255663d937d83e71a41e1aa0a8fa47489c484c03ae607c6e7b0"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "926b3d3f7e928602182ed52f94bb69495d3ef94366ef12a7c50a9fe3beee751a"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
    end
  end

  name "che-beta"
  desc "che-beta - versión pre-release de che para testing"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che-beta"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che-beta"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che-beta"
  end

  # No zap stanza required

end
