# This file was generated by GoReleaser. DO NOT EDIT.
cask "che-beta" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "09cdf856e5450f338fc3fd60cac94fbc0381827a85074e1549d67945c91a368f"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e122b7f1f4a006b79f49f43f963c027cb44b6b416692fe929f3ea22262a8aeec"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c515e3bee9e78ad9f6bfcd41474f0146c8b50563e07dbf2bea1e917c0f72a79"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "573bf69a88d043cc34d7c288c4ba3d876f96bf437e74a4543754dd616f39c055"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
    end
  end

  name "che-beta"
  desc "che-beta - versión pre-release de che para testing"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che"

  preflight do
    system "/bin/bash", "-c", 'brew list --cask che 2>/dev/null && (echo "che-beta: desinstalando cask estable para evitar conflicto de binario..." && brew uninstall --cask che) || true'
  end

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che"
  end

  # No zap stanza required

end
