# This file was generated by GoReleaser. DO NOT EDIT.
cask "che-beta" do
  version "1.0.0-rc.3"

  on_macos do
    on_intel do
      sha256 "dc9f9ec59b7492d44445a841f0d4d35ade9f489fef88e0eb9f791e06a145da88"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8194970bec30fcdec4ad3b343192335464a2e2077e346b108427ee8efeafb94"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c7acafac2847f500d9617f249a4f36f6dc4d51de665e4458876f3bc0ad6e558"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dee03695f2d7c8d50ec2fe405e283399e92bc14935292f7152f612d0b9da5b7f"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
    end
  end

  name "che-beta"
  desc "che-beta - versión pre-release de che para testing"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che-beta"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che-beta"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che-beta"
  end

  # No zap stanza required

end
