# This file was generated by GoReleaser. DO NOT EDIT.
cask "che" do
  version "0.0.47"

  on_macos do
    on_intel do
      sha256 "12868a28d1f3670ec3179eb0257918273ccbd55cf7134f3c3015762f64fc845d"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f197a1326d89bd7fd4e0d8cf6c0406690461d326452f4b2c6a7b103a7184e04b"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7a6e4fdb2805b4984243d51bf7927dfbde11f4f1b7af3156e7c115eaf1de437"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b369d2de51259258f8e3d9756c5b6ef61621d77b743d682a6252c9920ab8271"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
    end
  end

  name "che"
  desc "che - workflow estandarizado para trabajar con agentes de IA sobre issues de GitHub"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che"
  end

  # No zap stanza required

end
