# This file was generated by GoReleaser. DO NOT EDIT.
cask "che" do
  version "0.0.21"

  on_macos do
    on_intel do
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
      sha256 "4b0a7182dec594611a210f80948d3bb11f06653ce28b49f0de6ca741e3700c0e"
    end
    on_arm do
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
      sha256 "a6275fe12126ddef9fbedd46ee754da8532143621d9fb479f0c4cd0833a46a03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
      sha256 "d61a5ef6976bedb6175c82531e19aea03c19f60afcce8dfb0f510dd71fe3231d"
    end
    on_arm do
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
      sha256 "379f26db4e714b07dceaf4a039f6ac8c3d008f57cc2f73b335d7c41f8877d5f6"
    end
  end

  name "che"
  desc "che - workflow estandarizado para trabajar con agentes de IA sobre issues de GitHub"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che"
  end

  # No zap stanza required

end
