# This file was generated by GoReleaser. DO NOT EDIT.
cask "che" do
  version "0.0.41"

  on_macos do
    on_intel do
      sha256 "766514e893ad0ade845904e848fb273ec74be22e88fea7e5903b80ce89e1dee2"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d87644217dc726e7b133cad30779e50a6aa9272fddd231e76250e6ecbd7e925c"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92aed5bc5385c037bfaecfc4a74bd691e1ea4a4d8b490a7f55a2d0d06b996a71"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1177746f5b927c4cba5e73bee877e76786e97eafc5b4fb4efe89f13ef1c00cf1"
      url "https://github.com/chichex/che/releases/download/v#{version}/che_#{version}_linux_arm64.tar.gz"
    end
  end

  name "che"
  desc "che - workflow estandarizado para trabajar con agentes de IA sobre issues de GitHub"
  homepage "https://github.com/chichex/che"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "che"

  postflight do
    system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/che"
    system "codesign", "--sign", "-", "--force", "#{staged_path}/che"
  end

  # No zap stanza required

end
