# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvm < Formula
  desc "Claude Version Manager - profile manager for Claude Code"
  homepage "https://github.com/chichex/cvm"
  version "0.22.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chichex/cvm/releases/download/v0.22.2/cvm_0.22.2_darwin_amd64.tar.gz"
      sha256 "b19a87c31f197dde80f5706f0acec2954d08b33b7f8a28ffdc818dc4cb8d4dc0"

      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chichex/cvm/releases/download/v0.22.2/cvm_0.22.2_darwin_arm64.tar.gz"
      sha256 "d6c32c1ae8fd1ac19c5303f9517aac0af549f8afd2a16c026358f40d64843b24"

      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.22.2/cvm_0.22.2_linux_amd64.tar.gz"
      sha256 "b07e03d6ce6ca3a875429f303d657333ab9faf6bb593ce9011c163519a21530d"
      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.22.2/cvm_0.22.2_linux_arm64.tar.gz"
      sha256 "7202e26b7e2894d9639a5282caa9c1373ebadfa7119caacd379544ba17cb7b0f"
      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  def post_install
    if OS.mac?
      system "codesign", "--sign", "-", "--force", "#{bin}/cvm"
    end
  end

  test do
    system "#{bin}/cvm", "--version"
  end
end
