# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvm < Formula
  desc "Claude Version Manager - profile manager for Claude Code"
  homepage "https://github.com/chichex/cvm"
  version "0.19.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chichex/cvm/releases/download/v0.19.2/cvm_0.19.2_darwin_amd64.tar.gz"
      sha256 "5500c90d6d5b8b9aa27c2230a6982aed4aefc9deca6a690c59ea0b5666dad955"

      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chichex/cvm/releases/download/v0.19.2/cvm_0.19.2_darwin_arm64.tar.gz"
      sha256 "bea7b728c03e327a4d86f9b0592f1a404eda60d07720350381177e4a336c079b"

      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.19.2/cvm_0.19.2_linux_amd64.tar.gz"
      sha256 "df2f647ddf29eacf769b2eb5fc8801a95b492e8d526489a810db807e8fbe5886"
      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.19.2/cvm_0.19.2_linux_arm64.tar.gz"
      sha256 "16e3972ebfdd9f3d0592f76aba20bd4a36043703823f16c2ba876e38aef39e2e"
      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  def post_install
    if OS.mac?
      system "codesign", "--sign", "-", "--force", "#{bin}/cvm"
    end
  end

  test do
    system "#{bin}/cvm", "--version"
  end
end
