# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvm < Formula
  desc "Claude Version Manager - profile manager for Claude Code"
  homepage "https://github.com/chichex/cvm"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chichex/cvm/releases/download/v0.18.0/cvm_0.18.0_darwin_amd64.tar.gz"
      sha256 "e2cc3bf41a82e1a9d457fe75a2c2fc83ca4e60adb2b904d2fd8c8da99190f14e"

      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chichex/cvm/releases/download/v0.18.0/cvm_0.18.0_darwin_arm64.tar.gz"
      sha256 "06f8cb235429c64e10878b933ca60b353097b990ca3859f3095baae6b729dfc4"

      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.18.0/cvm_0.18.0_linux_amd64.tar.gz"
      sha256 "15bcb2b75e5aa2a0e6c96a18b9b58a443d418a0a1c877d3971136b8bf36740d5"
      define_method(:install) do
        bin.install "cvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chichex/cvm/releases/download/v0.18.0/cvm_0.18.0_linux_arm64.tar.gz"
      sha256 "8e82ff3b62923ca3d769c96641563e3c581217c0127757d1d9405ab534f30cef"
      define_method(:install) do
        bin.install "cvm"
      end
    end
  end

  test do
    system "#{bin}/cvm", "--version"
  end
end
